"""bsdf_reader プラグインシステム + LightToolsBsdfReader のテスト。"""

from __future__ import annotations

import textwrap
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from bsdf_sim.io.bsdf_reader import (
    BaseBsdfFileReader,
    _READER_REGISTRY,
    list_readers,
    load_bsdf_readers,
    read_bsdf_file,
    register_reader,
)
from bsdf_sim.io.parquet_schema import VALID_MODES, VALID_POLARIZATIONS, build_measured_dataframe


# ── フィクスチャ ──────────────────────────────────────────────────────────────

# 最小限の LightTools BSDF ファイル（3×4 グリッド、1 ブロック BRDF、1 ブロック BTDF）
_MINI_BSDF = textwrap.dedent("""\
    #Data Generated by MiniDiff Software version :2024.10.1
    #2025/01/01 00:00:00
    Model #: test_model
    Source\tMeasured
    Symmetry\tAsymmetric
    SpectralContent\tMonochrome
    ScatterAzimuth\t4
    0\t90\t180\t270
    ScatterRadial\t3
    0\t45\t90
    DataBegin

    AOI 0
    POI 0
    Side Front
    Wavelength 532
    ScatterType BRDF
    TIS 0.05
    1.0\t2.0\t3.0
    4.0\t5.0\t6.0
    7.0\t8.0\t9.0
    10.0\t11.0\t12.0

    AOI 20
    POI 0
    Side Front
    Wavelength 532
    ScatterType BTDF
    TIS 0.03
    0.1\t0.2\t0.3
    0.4\t0.5\t0.6
    0.7\t0.8\t0.9
    1.0\t1.1\t1.2
""")


@pytest.fixture()
def mini_bsdf_file(tmp_path: Path) -> Path:
    """最小限の LightTools BSDF ファイルを作成する。"""
    path = tmp_path / "test.bsdf"
    path.write_text(_MINI_BSDF, encoding="utf-8")
    return path


@pytest.fixture(autouse=True)
def clean_registry():
    """各テスト前後でレジストリをリセットする（テスト間干渉防止）。"""
    original = dict(_READER_REGISTRY)
    yield
    _READER_REGISTRY.clear()
    _READER_REGISTRY.update(original)


# ── build_measured_dataframe の is_btdf パラメータ ─────────────────────────────

class TestBuildMeasuredDataframeIsbtdf:
    """build_measured_dataframe の is_btdf 引数の動作確認。"""

    def _make_df(self, theta_i: float, is_btdf=None) -> pd.DataFrame:
        theta_s = np.array([0.0, 30.0, 45.0])
        phi_s   = np.array([0.0, 90.0, 180.0])
        bsdf    = np.array([1.0, 0.5, 0.2], dtype=np.float32)
        kwargs = {}
        if is_btdf is not None:
            kwargs["is_btdf"] = is_btdf
        return build_measured_dataframe(
            theta_s, phi_s, bsdf, theta_i, 0.0, 532.0, "Unpolarized", **kwargs
        )

    def test_none_small_aoi_defaults_to_brdf(self):
        df = self._make_df(theta_i=30.0)  # is_btdf=None
        assert (df["mode"] == "BRDF").all()

    def test_none_large_aoi_defaults_to_btdf(self):
        df = self._make_df(theta_i=91.0)  # is_btdf=None
        assert (df["mode"] == "BTDF").all()

    def test_explicit_true_overrides_small_aoi(self):
        df = self._make_df(theta_i=20.0, is_btdf=True)
        assert (df["mode"] == "BTDF").all()

    def test_explicit_false_overrides_large_aoi(self):
        df = self._make_df(theta_i=91.0, is_btdf=False)
        assert (df["mode"] == "BRDF").all()

    def test_wavelength_converted_to_um(self):
        df = self._make_df(theta_i=0.0)
        assert np.allclose(df["wavelength_um"].values, 0.532, atol=1e-4)

    def test_method_is_measured(self):
        df = self._make_df(theta_i=0.0)
        assert (df["method"] == "measured").all()

    def test_is_measured_flag(self):
        df = self._make_df(theta_i=0.0)
        assert df["is_measured"].all()


# ── BaseBsdfFileReader / レジストリ ───────────────────────────────────────────

class TestRegistry:
    """プラグインレジストリの動作確認。"""

    def test_register_reader_adds_to_registry(self):
        class MockReader(BaseBsdfFileReader):
            @classmethod
            def can_read(cls, path):
                return path.suffix == ".mock"
            @classmethod
            def read(cls, path):
                return []

        register_reader(MockReader)
        assert "MockReader" in _READER_REGISTRY
        assert "MockReader" in list_readers()

    def test_read_bsdf_file_uses_can_read(self, tmp_path):
        class AlwaysReader(BaseBsdfFileReader):
            @classmethod
            def can_read(cls, path):
                return True
            @classmethod
            def read(cls, path):
                return [pd.DataFrame({"x": [1]})]

        register_reader(AlwaysReader)
        dummy = tmp_path / "dummy.txt"
        dummy.write_text("hello")
        result = read_bsdf_file(dummy)
        assert len(result) == 1
        assert "x" in result[0].columns

    def test_read_bsdf_file_file_not_found(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            read_bsdf_file(tmp_path / "no_such_file.bsdf")

    def test_read_bsdf_file_no_reader_raises(self, tmp_path):
        dummy = tmp_path / "dummy.xyz"
        dummy.write_text("data")
        # レジストリが空の状態で呼ぶ
        _READER_REGISTRY.clear()
        with pytest.raises(ValueError, match="対応する BSDF リーダーが見つからない"):
            read_bsdf_file(dummy)

    def test_read_bsdf_file_by_name(self, tmp_path):
        class NamedReader(BaseBsdfFileReader):
            @classmethod
            def can_read(cls, path):
                return False  # 自動選択では使われないが名前指定なら使える
            @classmethod
            def read(cls, path):
                return [pd.DataFrame({"y": [2]})]

        register_reader(NamedReader)
        dummy = tmp_path / "dummy.dat"
        dummy.write_text("x")
        result = read_bsdf_file(dummy, reader_name="NamedReader")
        assert result[0]["y"].iloc[0] == 2

    def test_read_bsdf_file_unknown_reader_name(self, tmp_path):
        dummy = tmp_path / "dummy.dat"
        dummy.write_text("x")
        with pytest.raises(ValueError, match="未知のリーダー"):
            read_bsdf_file(dummy, reader_name="NoSuchReader")


# ── LightToolsBsdfReader ──────────────────────────────────────────────────────

class TestLightToolsBsdfReaderCanRead:
    """can_read() のテスト。"""

    def test_detects_minidiff_header(self, mini_bsdf_file):
        from custom_bsdf_readers.lightools_bsdf import LightToolsBsdfReader
        assert LightToolsBsdfReader.can_read(mini_bsdf_file) is True

    def test_rejects_non_minidiff(self, tmp_path):
        from custom_bsdf_readers.lightools_bsdf import LightToolsBsdfReader
        other = tmp_path / "other.bsdf"
        other.write_text("# Some other format\nData\n")
        assert LightToolsBsdfReader.can_read(other) is False

    def test_rejects_missing_file(self, tmp_path):
        from custom_bsdf_readers.lightools_bsdf import LightToolsBsdfReader
        assert LightToolsBsdfReader.can_read(tmp_path / "missing.bsdf") is False


class TestLightToolsBsdfReaderRead:
    """read() の結果検証。"""

    @pytest.fixture()
    def dfs(self, mini_bsdf_file):
        from custom_bsdf_readers.lightools_bsdf import LightToolsBsdfReader
        return LightToolsBsdfReader.read(mini_bsdf_file)

    def test_two_blocks(self, dfs):
        assert len(dfs) == 2

    def test_block_dtype_columns(self, dfs):
        required = {"u", "v", "theta_s_deg", "phi_s_deg", "theta_i_deg",
                    "phi_i_deg", "wavelength_um", "polarization", "mode",
                    "method", "bsdf", "is_measured", "log_rmse"}
        for df in dfs:
            assert required.issubset(df.columns)

    def test_first_block_brdf(self, dfs):
        assert (dfs[0]["mode"] == "BRDF").all()

    def test_second_block_btdf(self, dfs):
        assert (dfs[1]["mode"] == "BTDF").all()

    def test_first_block_aoi(self, dfs):
        assert np.allclose(dfs[0]["theta_i_deg"].values, 0.0)

    def test_second_block_aoi(self, dfs):
        assert np.allclose(dfs[1]["theta_i_deg"].values, 20.0)

    def test_wavelength_um(self, dfs):
        for df in dfs:
            assert np.allclose(df["wavelength_um"].values, 0.532, atol=1e-4)

    def test_row_count(self, dfs):
        # 3 radial × 4 azimuth = 12 rows per block
        for df in dfs:
            assert len(df) == 12

    def test_bsdf_values_first_block(self, dfs):
        # data_matrix[0, 0] = 1.0 (theta_s=0, phi_s=0)
        assert (dfs[0]["bsdf"].values >= 0.0).all()
        assert pytest.approx(dfs[0]["bsdf"].sum(), rel=1e-3) == pytest.approx(78.0)

    def test_bsdf_values_second_block(self, dfs):
        assert pytest.approx(dfs[1]["bsdf"].sum(), rel=1e-3) == pytest.approx(7.8)

    def test_polarization_unpolarized(self, dfs):
        for df in dfs:
            assert (df["polarization"] == "Unpolarized").all()

    def test_method_is_measured(self, dfs):
        for df in dfs:
            assert (df["method"] == "measured").all()

    def test_is_measured_flag(self, dfs):
        for df in dfs:
            assert df["is_measured"].all()

    def test_phi_s_values(self, dfs):
        phi_vals = set(dfs[0]["phi_s_deg"].round(0).astype(int).unique())
        assert phi_vals == {0, 90, 180, 270}

    def test_theta_s_values(self, dfs):
        theta_vals = sorted(dfs[0]["theta_s_deg"].unique())
        assert len(theta_vals) == 3
        assert pytest.approx(theta_vals[0]) == 0.0
        assert pytest.approx(theta_vals[1]) == 45.0
        assert pytest.approx(theta_vals[2]) == 90.0

    def test_uv_from_theta_phi(self, dfs):
        df = dfs[0]
        theta_rad = np.deg2rad(df["theta_s_deg"].values)
        phi_rad   = np.deg2rad(df["phi_s_deg"].values)
        u_expected = np.sin(theta_rad) * np.cos(phi_rad)
        v_expected = np.sin(theta_rad) * np.sin(phi_rad)
        assert np.allclose(df["u"].values, u_expected, atol=1e-4)
        assert np.allclose(df["v"].values, v_expected, atol=1e-4)


class TestLightToolsBsdfReaderInvalidFile:
    """不正ファイルへの対応テスト。"""

    def test_missing_scatter_azimuth_raises(self, tmp_path):
        from custom_bsdf_readers.lightools_bsdf import LightToolsBsdfReader
        bad = tmp_path / "bad.bsdf"
        bad.write_text("#Data Generated by MiniDiff Software version :1.0\nDataBegin\n")
        with pytest.raises(ValueError, match="ScatterAzimuth"):
            LightToolsBsdfReader.read(bad)

    def test_missing_data_begin_raises(self, tmp_path):
        from custom_bsdf_readers.lightools_bsdf import LightToolsBsdfReader
        bad = tmp_path / "bad.bsdf"
        bad.write_text(
            "#Data Generated by MiniDiff Software version :1.0\n"
            "ScatterAzimuth\t2\n0\t90\n"
            "ScatterRadial\t2\n0\t45\n"
            # DataBegin が無い
        )
        with pytest.raises(ValueError, match="DataBegin"):
            LightToolsBsdfReader.read(bad)


class TestLoadBsdfReadersPlugin:
    """load_bsdf_readers() プラグイン自動ロードのテスト。"""

    def test_load_registers_lightools_reader(self, tmp_path, monkeypatch):
        """custom_bsdf_readers/ フォルダから LightToolsBsdfReader を登録できる。"""
        import shutil
        import sys

        # custom_bsdf_readers/ を tmp_path にコピーして plugin_dir 指定でロード
        src_dir = Path(__file__).parent.parent / "custom_bsdf_readers"
        dst_dir = tmp_path / "custom_bsdf_readers"
        shutil.copytree(src_dir, dst_dir)

        # sys.path に追加してモジュール解決できるようにする
        monkeypatch.syspath_prepend(str(tmp_path))

        _READER_REGISTRY.clear()
        load_bsdf_readers(dst_dir)
        assert "LightToolsBsdfReader" in _READER_REGISTRY

    def test_nonexistent_plugin_dir_is_noop(self, tmp_path):
        """存在しないフォルダを指定しても例外が出ない。"""
        load_bsdf_readers(tmp_path / "no_such_dir")  # should not raise


class TestReadBsdfFileWithRealSample:
    """sample_inputs/ の実ファイルを使った統合テスト。"""

    SAMPLE = Path(__file__).parent.parent / "sample_inputs" / "BRDF_BTDF_LightTools.bsdf"

    @pytest.mark.skipif(
        not SAMPLE.exists(),
        reason="sample_inputs/BRDF_BTDF_LightTools.bsdf が存在しない",
    )
    def test_real_file_block_count(self):
        from custom_bsdf_readers.lightools_bsdf import LightToolsBsdfReader
        dfs = LightToolsBsdfReader.read(self.SAMPLE)
        assert len(dfs) == 24

    @pytest.mark.skipif(
        not SAMPLE.exists(),
        reason="sample_inputs/BRDF_BTDF_LightTools.bsdf が存在しない",
    )
    def test_real_file_brdf_btdf_split(self):
        from custom_bsdf_readers.lightools_bsdf import LightToolsBsdfReader
        dfs = LightToolsBsdfReader.read(self.SAMPLE)
        df_all = pd.concat(dfs, ignore_index=True)
        brdf_blocks = sum(1 for d in dfs if (d["mode"] == "BRDF").all())
        btdf_blocks = sum(1 for d in dfs if (d["mode"] == "BTDF").all())
        assert brdf_blocks == 12
        assert btdf_blocks == 12

    @pytest.mark.skipif(
        not SAMPLE.exists(),
        reason="sample_inputs/BRDF_BTDF_LightTools.bsdf が存在しない",
    )
    def test_real_file_row_count(self):
        from custom_bsdf_readers.lightools_bsdf import LightToolsBsdfReader
        dfs = LightToolsBsdfReader.read(self.SAMPLE)
        # 91 radial × 361 azimuth = 32851 rows per block × 24 blocks
        total = sum(len(d) for d in dfs)
        assert total == 91 * 361 * 24

    @pytest.mark.skipif(
        not SAMPLE.exists(),
        reason="sample_inputs/BRDF_BTDF_LightTools.bsdf が存在しない",
    )
    def test_real_file_bsdf_mostly_nonnegative(self):
        """実測データは概ね非負。測定ノイズによる微小な負値は許容する。"""
        from custom_bsdf_readers.lightools_bsdf import LightToolsBsdfReader
        dfs = LightToolsBsdfReader.read(self.SAMPLE)
        for df in dfs:
            bsdf = df["bsdf"].values
            # 大部分が非負であることを確認（1% 以内の負値を許容）
            neg_ratio = (bsdf < 0).sum() / len(bsdf)
            assert neg_ratio < 0.01, f"負値の割合が多すぎる: {neg_ratio:.1%}"
            # 極端な負値がないことを確認
            assert bsdf.min() > -1.0

    @pytest.mark.skipif(
        not SAMPLE.exists(),
        reason="sample_inputs/BRDF_BTDF_LightTools.bsdf が存在しない",
    )
    def test_real_file_via_read_bsdf_file(self):
        from custom_bsdf_readers.lightools_bsdf import LightToolsBsdfReader
        register_reader(LightToolsBsdfReader)
        dfs = read_bsdf_file(self.SAMPLE)
        assert len(dfs) == 24
