"""LightTools / MiniDiff Software BSDF ファイルリーダー（プラグイン）。

フォーマット仕様:
  - 生成ソフト: MiniDiff Software（LightTools 用 BSDF 出力）
  - 拡張子: .bsdf
  - エンコード: ASCII / UTF-8
  - 1 ファイルに複数ブロック（AOI × 波長 × BRDF/BTDF）

ファイル構造::

    #Data Generated by MiniDiff Software version :YYYY.MM.R
    #YYYY/MM/DD HH:MM:SS
    Model #: <model_name>
    Source	Measured
    Symmetry	Asymmetric
    SpectralContent	Monochrome
    ScatterAzimuth	361
    0	1	2	...	360
    ScatterRadial	91
    0	1	2	...	90
    DataBegin
    [空行]
    AOI <angle_deg>
    POI <angle_deg>
    Side Front|Back
    Wavelength <wavelength_nm>
    ScatterType BRDF|BTDF
    TIS <value>
    <91行 × 361列のタブ区切り BSDF 値>
    [次のブロック...]

サンプルファイル: sample_inputs/BRDF_BTDF_LightTools.bsdf

使用方法（Python）::

    from bsdf_sim.io.bsdf_reader import load_bsdf_readers, read_bsdf_file

    load_bsdf_readers()
    dfs = read_bsdf_file("sample_inputs/BRDF_BTDF_LightTools.bsdf")
    df = pd.concat(dfs, ignore_index=True)
"""

from __future__ import annotations

import logging
from pathlib import Path

import numpy as np
import pandas as pd

from bsdf_sim.io.bsdf_reader import BaseBsdfFileReader
from bsdf_sim.io.parquet_schema import build_measured_dataframe

logger = logging.getLogger(__name__)

# MiniDiff ファイルの識別文字列
_MAGIC = "MiniDiff Software"

# ブロックヘッダのキー
_KEY_AOI          = "AOI"
_KEY_POI          = "POI"
_KEY_SIDE         = "Side"
_KEY_WAVELENGTH   = "Wavelength"
_KEY_SCATTER_TYPE = "ScatterType"
_KEY_TIS          = "TIS"


class LightToolsBsdfReader(BaseBsdfFileReader):
    """LightTools / MiniDiff Software の .bsdf ファイルリーダー。

    ファイルヘッダの "MiniDiff Software" 文字列で識別する。
    BRDF/BTDF は ScatterType フィールドで明示的に判定する。
    """

    @classmethod
    def can_read(cls, path: Path) -> bool:
        """MiniDiff Software 生成ファイルかどうかを判定する。

        先頭行に "MiniDiff Software" が含まれていれば True を返す。
        """
        try:
            with path.open("r", encoding="utf-8", errors="replace") as f:
                first_line = f.readline()
            return _MAGIC in first_line
        except OSError:
            return False

    @classmethod
    def read(cls, path: Path) -> list[pd.DataFrame]:
        """BSDF ファイルを読み込み、ブロックごとの DataFrame リストを返す。

        Args:
            path: .bsdf ファイルパス

        Returns:
            DataFrame のリスト（各要素 = 1 測定ブロック）

        Raises:
            ValueError: ファイル形式が不正な場合
        """
        path = Path(path)
        text = path.read_text(encoding="utf-8", errors="replace")
        lines = text.splitlines()

        azimuth_angles, radial_angles = cls._parse_file_header(lines)
        n_az = len(azimuth_angles)  # 通常 361
        n_rad = len(radial_angles)  # 通常 91

        # DataBegin 以降をブロックに分割して解析
        # データ行列は n_az 行 × n_rad 列（方位角ごとに 1 行）
        data_start = cls._find_data_begin(lines)
        blocks = cls._split_blocks(lines[data_start:], n_az)

        result: list[pd.DataFrame] = []
        for i, block in enumerate(blocks):
            try:
                df = cls._parse_block(block, azimuth_angles, radial_angles, n_az, n_rad)
                result.append(df)
                logger.debug(
                    f"ブロック {i + 1}/{len(blocks)} 読み込み完了: "
                    f"AOI={block['meta'].get(_KEY_AOI)} "
                    f"WL={block['meta'].get(_KEY_WAVELENGTH)} nm "
                    f"Type={block['meta'].get(_KEY_SCATTER_TYPE)}"
                )
            except Exception as e:
                logger.warning(f"ブロック {i + 1} の解析に失敗（スキップ）: {e}")

        logger.info(
            f"LightTools BSDF 読み込み完了: {path.name} "
            f"({len(result)}/{len(blocks)} ブロック)"
        )
        return result

    # ── 内部メソッド ────────────────────────────────────────────────────────────

    @staticmethod
    def _parse_file_header(lines: list[str]) -> tuple[np.ndarray, np.ndarray]:
        """ファイルヘッダから ScatterAzimuth・ScatterRadial 角度配列を取得する。

        Returns:
            (azimuth_angles, radial_angles) — いずれも float64 の 1D 配列
        """
        azimuth_angles: np.ndarray | None = None
        radial_angles:  np.ndarray | None = None
        i = 0
        while i < len(lines):
            line = lines[i].strip()
            if line.startswith("ScatterAzimuth"):
                parts = line.split()
                n_az = int(parts[1]) if len(parts) > 1 else 0
                i += 1
                azimuth_angles = np.array(lines[i].split(), dtype=np.float64)
                if len(azimuth_angles) != n_az:
                    logger.warning(
                        f"ScatterAzimuth: 宣言値 {n_az} != 実際の値数 {len(azimuth_angles)}"
                    )
            elif line.startswith("ScatterRadial"):
                parts = line.split()
                n_rad = int(parts[1]) if len(parts) > 1 else 0
                i += 1
                radial_angles = np.array(lines[i].split(), dtype=np.float64)
                if len(radial_angles) != n_rad:
                    logger.warning(
                        f"ScatterRadial: 宣言値 {n_rad} != 実際の値数 {len(radial_angles)}"
                    )
            elif line == "DataBegin":
                break
            i += 1

        if azimuth_angles is None or radial_angles is None:
            raise ValueError(
                "ScatterAzimuth または ScatterRadial がヘッダに見つからない。"
                "LightTools BSDF フォーマットか確認してください。"
            )
        return azimuth_angles, radial_angles

    @staticmethod
    def _find_data_begin(lines: list[str]) -> int:
        """DataBegin 行のインデックス（+1）を返す。"""
        for i, line in enumerate(lines):
            if line.strip() == "DataBegin":
                return i + 1
        raise ValueError("'DataBegin' 行がファイルに見つからない。")

    @staticmethod
    def _split_blocks(
        data_lines: list[str], n_az: int
    ) -> list[dict]:
        """データ部をブロックに分割する。

        各ブロック = メタデータ（AOI/POI/Side/Wavelength/ScatterType/TIS）
                   + n_az 行のデータ行列（方位角ごとに 1 行）

        Args:
            data_lines: DataBegin 以降の行リスト
            n_az: ScatterAzimuth 数（データ行列の行数）

        Returns:
            ブロック辞書のリスト: {"meta": dict, "data_lines": list[str]}
        """
        blocks: list[dict] = []
        meta_keys = {_KEY_AOI, _KEY_POI, _KEY_SIDE, _KEY_WAVELENGTH, _KEY_SCATTER_TYPE, _KEY_TIS}
        current_meta: dict[str, str] = {}
        current_data: list[str] = []
        state = "meta"  # "meta" or "data"

        for line in data_lines:
            stripped = line.strip()
            if not stripped:
                continue

            if state == "meta":
                parts = stripped.split(None, 1)
                key = parts[0]
                if key in meta_keys and len(parts) == 2:
                    current_meta[key] = parts[1]
                    # TIS が来たらデータ行に切り替え
                    if key == _KEY_TIS:
                        state = "data"
            elif state == "data":
                current_data.append(stripped)
                if len(current_data) == n_az:
                    blocks.append({"meta": current_meta, "data_lines": current_data})
                    current_meta = {}
                    current_data = []
                    state = "meta"

        return blocks

    @staticmethod
    def _parse_block(
        block: dict,
        azimuth_angles: np.ndarray,
        radial_angles: np.ndarray,
        n_az: int,
        n_rad: int,
    ) -> pd.DataFrame:
        """ブロック辞書から DataFrame を構築する。

        散乱角グリッド（ScatterAzimuth × ScatterRadial）を展開し、
        build_measured_dataframe() に渡す。
        データ行列は (n_az, n_rad) 形状（方位角が行、径方向が列）。
        """
        meta = block["meta"]

        theta_i_deg  = float(meta[_KEY_AOI])
        phi_i_deg    = float(meta[_KEY_POI])
        wavelength_nm = float(meta[_KEY_WAVELENGTH])
        scatter_type = meta[_KEY_SCATTER_TYPE].strip().upper()
        is_btdf = scatter_type == "BTDF"

        # データ行列: shape (n_az, n_rad) — 方位角ごとに 1 行、各行に径方向値
        # data_matrix[i_phi, i_theta] = BSDF at (azimuth[i_phi], radial[i_theta])
        data_matrix = np.empty((n_az, n_rad), dtype=np.float32)
        for i, row_str in enumerate(block["data_lines"]):
            values = np.array(row_str.split(), dtype=np.float32)
            if len(values) != n_rad:
                raise ValueError(
                    f"行 {i}: 値の数 {len(values)} が ScatterRadial 数 {n_rad} と不一致"
                )
            data_matrix[i] = values

        # 散乱角グリッドの展開
        # phi_grid[i_phi, i_theta] = azimuth_angles[i_phi]
        # theta_grid[i_phi, i_theta] = radial_angles[i_theta]
        phi_grid_deg   = np.tile(azimuth_angles[:, np.newaxis], (1, n_rad))  # (n_az, n_rad)
        theta_grid_deg = np.tile(radial_angles[np.newaxis, :], (n_az, 1))    # (n_az, n_rad)

        theta_s_flat = theta_grid_deg.ravel().astype(np.float64)
        phi_s_flat   = phi_grid_deg.ravel().astype(np.float64)
        bsdf_flat    = data_matrix.ravel().astype(np.float32)

        return build_measured_dataframe(
            theta_s_deg=theta_s_flat,
            phi_s_deg=phi_s_flat,
            bsdf_values=bsdf_flat,
            theta_i_deg=theta_i_deg,
            phi_i_deg=phi_i_deg,
            wavelength_nm=wavelength_nm,
            polarization="Unpolarized",
            is_btdf=is_btdf,
        )
